### ISSUE TITLE
Error when running track.py

### ISSUE THREAD

**Issue by wolfassi123** [mikel-brostrom/yolo_tracking#1356]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Was testing a few trackers and then suddenly the code stopped working and got the following error:
`
AttributeError: 'PyTorchBackend' object has no attribute 'preprocess'
`
I am guessing it might be something that has to do with versioning maybe. Nothing explains the error besides this. Anyone faced this and fixed it?

Traceback:

  File "/content/yolo_tracking/tracking/track.py", line 172, in <module>
    run(opt)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/yolo_tracking/tracking/track.py", line 101, in run
    for r in results:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/predictor.py", line 252, in stream_inference
    self.run_callbacks('on_predict_start')
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/predictor.py", line 377, in run_callbacks
    callback(self)
  File "/content/yolo_tracking/tracking/track.py", line 51, in on_predict_start
    tracker.model.warmup()
  File "/content/yolo_tracking/boxmot/appearance/backends/base_backend.py", line 94, in warmup
    im = self.preprocess(xyxys=np.array([[0, 0, 128, 256]]), img=im)

**Comment by mikel-brostrom** [comment]
This repo has undergone serveral major refactors in the past couple of days. If you experience issues I recommend you to reclone and start from a clean slate :smile:

**Comment by demuxin** [comment]
I'm having a similar problem with the master branch, my code is up to date

**Comment by demuxin** [comment]
I encounter the same problem and solved it by #https://github.com/mikel-brostrom/yolo_tracking/issues/1263#issuecomment-1898657606

**Comment by liuliuliu1111** [comment]
I met the same error. In my case, it may be because I did not follow the installation instructions in the readme file and installed the cuda version of torch myself. By the way, I would like to ask how I can use the cuda version of torch, because I want to train my own custom data @mikel-brostrom. Thanks a lot!

**Comment by kuaihuolinlim** [comment]
After installing the CUDA version of PyTorch, I encountered the same error. How can I install the CUDA version of PyTorch without encountering this error?

**Comment by mikel-brostrom** [comment]
Should be fixed

**Comment by liuliuliu1111** [comment]
It still doesn't seem right, the error still exists in my case. @mikel-brostrom

**Comment by jmudy** [comment]
I think you were getting that error when installing the cuda version of torch. I had the same thing happen to me a few weeks ago. With the latest changes in the repository it works without problems and I don't get that error.
