### ISSUE TITLE
Memory overflow in `KalmanFilter` class due to unbounded `self.history_obs` list in long-running instances of OCSort and DeepOCSort

### ISSUE THREAD

**Issue by edblu1** [mikel-brostrom/yolo_tracking#1357]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

Hello,
We’ve been implementing multiple instances of the OCSort tracker from your repository for long-lived object tracking tasks (see our object-tracker repository at https://github.com/starwit/object-tracker) and encountered a memory management issue. Specifically, when tracking mostly static objects like a parking lot. 
The `self.history_obs` list in `boxmot.motion.kalman_filters.ocsort_kf.py` (and also in `boxmot.motion.kalman_filters.deepocsort_kf.py`) grows indefinitely, leading to increased processing times and potential memory overflows.
While the `KalmanBoxTracker` implementation in `boxmot.trackers.ocsort.ocsort.py` and `boxmot.trackers.deepocsort.deep_ocsort.py` has been updated to use `collections.deque` to manage `self.history` and `self.history_observations` in a memory-efficient way (v10.0.57), the `KalmanFilter` class still uses a list for `history_obs`, which can cause problems in long-running, mostly static instances.
Proposed fix: We recommend updating `history_obs` in `KalmanFilter` to also use `collections.deque` with a set `maxlen` to prevent uncontrolled growth of the list.
Question: Would you prefer we contribute a pull request with this modification, or is there already a planned update to address this? Thanks for looking into this.

### Environment

- Python 3.10.13
- boxmot 10.0.57

### Minimal Reproducible Example
Setup: Run the `OCSort` tracker on a dataset where the frames contain mostly static objects, or just continuously feed a static image with objects into the `tracker.update` method. 
Expected behavior: The size of `self.history_obs` of the `KalmanFilter` objects should remain manageable, possibly by discarding old entries that are not critical for current updates.
Actual behavior: The `self.history_obs` list sizes grow indefinitely as more frames are processed.

**Comment by mikel-brostrom** [comment]
Should be fixed @edblu1 . All lists, which could potentially grow to an arbitrary length are now deques of size 50 🚀

**Comment by edblu1** [comment]
Perfect, thanks!

**Comment by edblu1** [comment]
Hi @mikel-brostrom, we noticed that the memory overflow problem persists even after the fix. This is because the `self.history_obs` dictionary is reinitialized without the `maxlen` parameter in the `unfreeze` method (`ocsort_kf.py`).
We'd love to create a PR, but we haven't found any notes about contributions in this repo. As it's a trivial fix anyway it is probably easiest if you fix it. In case that you need any help or further investigation, we'd be happy to contribute!

**Comment by mikel-brostrom** [comment]
Fixed. New pkg released as well 😄

**Comment by edblu1** [comment]
That was fast! Thanks 😊
