### ISSUE TITLE
could not run track.py with my own yolox_s.pth

### ISSUE THREAD

**Issue by NickFryXX** [mikel-brostrom/yolo_tracking#974]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

(yolov5) PS F:\YOLO\yolo_tracking-10.1> python examples/track.py --source F:\home\mix\images --yolo-model F:\YOLO\yolo_tracking-10.1\ckpt\yolox_s.pth --reid-model F:\YOLO\yolo_tracking-10.1\ckpt\osnet_x0_25_msmt17.pt --save --tracking-method strongsort
2023-06-29 10:50:29.884 | INFO     | boxmot.utils.torch_utils:select_device:52 - Yolo Tracking v10.0.15 🚀 Python-3.7.0 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3070, 8192MiB)

2023-06-29 10:50:29.885 | INFO     | __main__:run:67 - {'yolo_model': WindowsPath('F:/YOLO/yolo_tracking-10.1/ckpt/yolox_s.pth'), 'reid_model': WindowsPath('F:/YOLO/yolo_tracking-10.1/ckpt/osnet_x0_25_msmt17.pt'), 'tracking_method': 'strongsort', 'source': 'F:\\home\\mix\\images', 'imgsz': [640], 'conf': 0.
5, 'iou': 0.7, 'device': '', 'show': False, 'save': True, 'classes': None, 'project': WindowsPath('D:/Anaconda/envs/yolov5/Lib/site-packages/boxmot-10.0.15-py3.7.egg/runs/track'), 'name': 'exp', 'exist_ok': False, 'half': False, 'vid_stride': 1, 'hide_label': False, 'hide_conf': False, 'save_txt': False, 'save_id_crops': False, 'save_mot': False}
2023-06-29 10:50:32.325 | SUCCESS  | boxmot.deep.reid_model_factory:load_pretrained_weights:230 - Successfully loaded pretrained weights from "F:\YOLO\yolo_tracking-10.1\ckpt\osnet_x0_25_msmt17.pt"
2023-06-29 10:50:32.325 | WARNING  | boxmot.deep.reid_model_factory:load_pretrained_weights:234 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')
The console stream is logged into C:\Users\User\sg_logs\console.log
[2023-06-29 10:50:32] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-06-29 10:50:32] WARNING - redirects.py - NOTE: Redirects are currently not supported in Windows or MacOs.
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\_distutils_hack\__init__.py:35: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-06-29 10:50:34] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-06-29 10:50:34] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-06-29 10:50:34] WARNING - export.py - Failed to import pytorch_quantization
[2023-06-29 10:50:34] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
[2023-06-29 10:50:34] WARNING - env_sanity_check.py - Failed to verify operating system: Deci officially supports only Linux kernels. Some features may not work as expected.

F:\YOLO\yolo_tracking-10.1\ckpt\yolox_s.pth This is the path to my own yolox model. I pretrained this model with official YoloX code. It seems like track.py can't load my model and still use yolov8n.pt for detection.

2023-06-29 10:50:34.350 | INFO     | __main__:run:184 - image 1/1500 F:\home\mix\images\000001.jpg: 512x640 (no detections), YOLO 24.0ms, TRACKING 0.0ms
2023-06-29 10:50:34.373 | INFO     | __main__:run:184 - image 2/1500 F:\home\mix\images\000002.jpg: 512x640 (no detections), YOLO 17.0ms, TRACKING 0.0ms
2023-06-29 10:50:34.399 | INFO     | __main__:run:184 - image 3/1500 F:\home\mix\images\000003.jpg: 512x640 (no detections), YOLO 20.0ms, TRACKING 0.0ms
2023-06-29 10:50:34.421 | INFO     | __main__:run:184 - image 4/1500 F:\home\mix\images\000004.jpg: 512x640 (no detections), YOLO 17.0ms, TRACKING 0.0ms
2023-06-29 10:50:34.446 | INFO     | __main__:run:184 - image 5/1500 F:\home\mix\images\000005.jpg: 512x640 (no detections), YOLO 18.0ms, TRACKING 0.0ms
2023-06-29 10:50:34.474 | INFO     | __main__:run:184 - image 6/1500 F:\home\mix\images\000006.jpg: 512x640 (no detections), YOLO 22.0ms, TRACKING 0.0ms

It's clearly that track.py doesn't have  any detections. While my model can run perfectly with the official YoloX code

**Comment by mikel-brostrom** [comment]
YoloX is supported through SG. So the official repo is not supported. But can add the official YOLOX to the yolo_backends file :smile: . I suggest that you follow the example for custom model tracking meanwhile

**Comment by NickFryXX** [comment]
Thank you for your reply. I have been trying to solve this problem recently. With reference to your example, I have made some progress.

**Comment by mikel-brostrom** [comment]
Should work now @NickFryXX !

**Comment by mikel-brostrom** [comment]
You maybe need to do some custom modifications here: https://github.com/mikel-brostrom/yolo_tracking/blob/master/examples/multi_yolo_backend.py to get it working.

**Comment by NQHuy1905** [comment]
@mikel-brostrom hi, i still get no detection even i use pretrain download from official YoloX code
